# Generated by Django 2.0.5 on 2018-06-12 19:35

import correspondencia.carga_archivos
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agr_retencion_documental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AGRUPACION_TABLAS_RETENCION',
            },
        ),
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondencia_x_oficina', models.CharField(max_length=3)),
                ('consecutivo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'CONSECUTIVO',
            },
        ),
        migrations.CreateModel(
            name='Correspondencia_entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField()),
                ('hora_recibido', models.TimeField()),
                ('numero_radicacion', models.CharField(max_length=30)),
                ('correspondencia_x_oficina', models.CharField(max_length=2)),
                ('asunto', models.CharField(max_length=200)),
                ('observacion', models.TextField(null=True)),
                ('fecha_documento_radicado', models.DateField()),
                ('numero_folios_documento', models.CharField(max_length=4)),
                ('archivo_digital', models.FileField(blank=True, upload_to=correspondencia.carga_archivos.generar_ruta_archivo)),
                ('visualizado', models.BooleanField(default=False)),
                ('anulado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CORRESPONDENCIA_ENTRADA',
            },
        ),
        migrations.CreateModel(
            name='Correspondencia_salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('fecha_documento', models.DateField()),
                ('fecha_envio', models.DateField()),
                ('asunto', models.CharField(max_length=200)),
                ('observacion', models.TextField(null=True)),
                ('numero_folios_documento', models.CharField(max_length=4)),
                ('numero_guia', models.CharField(max_length=30)),
                ('archivo_adjunto', models.FileField(blank=True, upload_to=correspondencia.carga_archivos.generar_ruta_archivo)),
            ],
            options={
                'db_table': 'CORRESPONDENCIA_SALIDA',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('dependencia', models.TextField()),
            ],
            options={
                'db_table': 'DEPENDENCIA_ALCALDIA',
            },
        ),
        migrations.CreateModel(
            name='Dependencia_origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Dependencia')),
            ],
            options={
                'db_table': 'DEPENDENCIA_ORIGEN',
            },
        ),
        migrations.CreateModel(
            name='Empresa_mensajeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('numero_id', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=100)),
                ('pagina_web', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'EMPRESA_MENSAJERIA',
            },
        ),
        migrations.CreateModel(
            name='Evento_correspondencia_entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('evento_realizado', models.CharField(max_length=100)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Correspondencia_entrada')),
            ],
            options={
                'db_table': 'EVENTO_CORRESPONDENCIA_ENTRADA',
            },
        ),
        migrations.CreateModel(
            name='Lectura_correspondencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('documento_fisico', models.BooleanField()),
                ('documento_virtual', models.BooleanField()),
                ('observacion', models.TextField()),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Correspondencia_entrada')),
            ],
            options={
                'db_table': 'LECTURA_CORRESPONDENCIA',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('oficina', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'OFICINA_RECEPCION_CORRESPONDENCIA',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('numero_id', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Serie_documental_Retencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('serie_documental', models.TextField()),
            ],
            options={
                'db_table': 'SERIE_DOCUMENTAL_RETENCION',
            },
        ),
        migrations.CreateModel(
            name='Subserie_documental_Retencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('subserie_documental', models.TextField()),
            ],
            options={
                'db_table': 'SUBSERIE_DOCUMENTAL_RETENCION',
            },
        ),
        migrations.CreateModel(
            name='Tipo_correspondencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'TIPO_CORRESPONDENCIA',
            },
        ),
        migrations.CreateModel(
            name='Tipo_documental_Retencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documental', models.TextField()),
            ],
            options={
                'db_table': 'TIPO_DOCUMENTAL_RETENCION',
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'TIPO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='Tipo_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=4)),
                ('detalle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TIPO_ID',
            },
        ),
        migrations.CreateModel(
            name='Tipo_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TIPO_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Usuario_x_oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Oficina')),
            ],
            options={
                'db_table': 'USUARIO_X_OFICINA_CORRESPONDENCIA',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario_x_oficina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Usuario'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_id'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Usuario'),
        ),
        migrations.AddField(
            model_name='lectura_correspondencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Usuario'),
        ),
        migrations.AddField(
            model_name='evento_correspondencia_entrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Usuario'),
        ),
        migrations.AddField(
            model_name='empresa_mensajeria',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_id'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Dependencia'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='empresa_mensajeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Empresa_mensajeria'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Persona'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='serie_documental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Serie_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='subserie_documental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Subserie_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='tipo_correspondencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_correspondencia'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='tipo_documental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_documento'),
        ),
        migrations.AddField(
            model_name='correspondencia_salida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Usuario'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Dependencia'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='dependencia_origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Dependencia_origen'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Persona'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='serie_documental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Serie_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='subserie_documental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Subserie_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='tipo_correspondencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_correspondencia'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='tipo_documental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_documento'),
        ),
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Usuario'),
        ),
        migrations.AddField(
            model_name='agr_retencion_documental',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Dependencia'),
        ),
        migrations.AddField(
            model_name='agr_retencion_documental',
            name='serie_documental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Serie_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='agr_retencion_documental',
            name='subserie_documental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Subserie_documental_Retencion'),
        ),
        migrations.AddField(
            model_name='agr_retencion_documental',
            name='tipo_documental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Tipo_documental_Retencion'),
        ),
    ]
