# Generated by Django 2.0.5 on 2018-08-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia_entrada',
            name='copia',
            field=models.BooleanField(default=False),
        ),
    ]
