# Generated by Django 2.0.5 on 2018-09-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_correspondencia_entrada_copia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copia_correspondencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Correspondencia_entrada')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Dependencia')),
            ],
            options={
                'db_table': 'COPIA_CORRESPONDENCIA',
            },
        ),
    ]
