# Generated by Django 2.0.5 on 2018-09-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_copia_correspondencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copia_correspondencia',
            name='correspondencia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='copia_correspondencia',
            name='dependencia',
            field=models.TextField(),
        ),
    ]
