# Generated by Django 2.0.5 on 2018-09-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_auto_20180904_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copia_correspondencia',
            name='correspondencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Correspondencia_entrada'),
        ),
        migrations.AlterField(
            model_name='copia_correspondencia',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='correspondencia.Dependencia'),
        ),
    ]
